### ISSUE TITLE
Licence restrictions

### ISSUE THREAD

**Issue by dylanede** [theban/interval-tree#2]
Would it be possible to release this under a more permissive licence? I'd like to make use of interval-tree in some of my crates, but I only release under permissive licences (typically dual MIT/Apache, which is the de facto standard in the Rust community).

I've made some heavy modifications to the library privately which I would be willing to post as a PR if the licence is changed, including support for arbitrary key types and a more general range implementation (Inclusive, exclusive and unbounded bounds), `into_iter` support, an "entry API" implementation similar to that found in the standard library and other usability improvements.

Thanks in advance.

**Comment by eqv** [comment]
Done, I'm looking forward to your PR.

**Comment by eqv** [comment]
@dylanede do you still consider to add a PR?
